TeleSpecialists.Web/Controllers/CaseController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeleSpecialists.BLL;
using TeleSpecialists.BLL.Extensions;
using TeleSpecialists.BLL.Helpers;
using TeleSpecialists.BLL.Model;
using TeleSpecialists.BLL.Service;
using TeleSpecialists.BLL.ViewModels;
using TeleSpecialists.BLL.ViewModels.FacilityUser;
using TeleSpecialists.Models;
using TeleSpecialists.Web.Hubs;
using TeleSpecialists.Web.Models;
using TeleSpecialists.BLL.Service.CaseServices;
using Kendo.DynamicLinq;

namespace TeleSpecialists.Controllers
{
    /// <summary>   
    /// Will Require Admin Authentication
    /// </summary>
    [Authorize]
    public class CaseController : BaseController
    {
        private readonly AdminService _adminService;
        private readonly CaseService _caseService;
        private readonly CaseGridService _caseGridService;
        private readonly FacilityService _facilityService;
        private readonly ContactService _contactService;
        private readonly UCLService _uclService;
        private readonly FacilityPhysicianService _facilityPhysicianService;
        private readonly EntityNoteService _entityNotesService;
        private readonly CallhistoryService _callHistoryService;
        private readonly CaseAssignHistoryService _caseAssignHistoryService;
        private readonly PhysicianStatusService _physicianStatusService;
        private readonly NIHStrokeScaleService _nihStrokeScaleService;
        private readonly LookupService _lookUpService;
        private readonly PhysicianService _physician;
        private readonly PhysicianStatusLogService _physicianStatusLogService;
        private readonly CaseTemplateService _templateService;
        private readonly CaseGeneratedTemplateService _generateTemplateService;
        private readonly EAlertFacilitiesService _ealertFacilitiesService;
        private readonly FacilityContractService _facilityContractService;
        private readonly RootCauseService _rootCauseService;
        private readonly CaseReviewTemplateService _casereviewTemplateService;
        private readonly PhysicianCaseTempService _physicianCaseTempService;
        private readonly PostAcuteCareService _homeHealthService;
        private readonly CasCancelledTypeService _casCancelledTypeService;
        private readonly DiagnosisCodesService _diagnosisCodesService;
        private readonly HospitalprotocolServices _Protocols;
        private readonly OnBoardedServices _OnBoardedServices;
        private readonly TokenService _tokenservice;
        private readonly user_fcm_notification _user_Fcm_Notification;
        private readonly FireBaseUserMailService _fireBaseUserMailService;
        private readonly MockCaseService _mockCaseService;
        private readonly CaseRejectService _caseRejectService;

        private const int _min_dob_year = 1753;
        private static bool isCalculateBill { get; set; }

        /// <summary>
        /// Constructor, initialize instances here.
        /// </summary>
        public CaseController() : base()
        {
            _adminService = new AdminService();
            _caseService = new CaseService();
            _uclService = new UCLService();
            _facilityService = new FacilityService();
            _facilityPhysicianService = new FacilityPhysicianService();
            _entityNotesService = new EntityNoteService();
            _contactService = new ContactService();
            _callHistoryService = new CallhistoryService();
            _caseAssignHistoryService = new CaseAssignHistoryService();
            _physicianStatusService = new PhysicianStatusService();

            _physician = new PhysicianService();
            _physicianStatusLogService = new PhysicianStatusLogService();
            _nihStrokeScaleService = new NIHStrokeScaleService();
            _templateService = new CaseTemplateService();
            _lookUpService = new LookupService();
            _generateTemplateService = new CaseGeneratedTemplateService();
            _ealertFacilitiesService = new EAlertFacilitiesService();
            _facilityContractService = new FacilityContractService();
            _rootCauseService = new RootCauseService();
            _caseGridService = new CaseGridService();
            _physicianCaseTempService = new PhysicianCaseTempService();
            _casereviewTemplateService = new CaseReviewTemplateService();
            _homeHealthService = new PostAcuteCareService();
            _casCancelledTypeService = new CasCancelledTypeService();
            _diagnosisCodesService = new DiagnosisCodesService();
            _Protocols = new HospitalprotocolServices();
            _tokenservice = new TokenService();
            _user_Fcm_Notification = new user_fcm_notification();
            _fireBaseUserMailService = new FireBaseUserMailService();
            _OnBoardedServices = new OnBoardedServices();
            _mockCaseService = new MockCaseService();
            _caseRejectService = new CaseRejectService();
        }

        public ActionResult Index()
        {
            try
            {

                if (TempData.ContainsKey("Message"))
                    TempData.Remove("Message");

                bool allowListing = true;
                if (User.IsInRole(UserRoles.FacilityAdmin.ToDescription()))
                {
                    var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
                                            .Select(x => x.Facility).ToList();
                    if (facilities.Count < 1)
                    {
                        allowListing = false;
                        ViewBag.FacilityAdminMessage = "No Facility assigned to the user. Please contact your system administrator.";
                    }
                }
                if (User.IsInRole(UserRoles.FacilityPhysician.ToDescription()))
                {
                    var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
                                            .Select(x => x.Facility).ToList();
                    if (facilities.Count < 1)
                    {
                        allowListing = false;
                        ViewBag.FacilityAdminMessage = "No Facility assigned to the user. Please contact your system administrator.";
                    }
                }
                //  Commented Temporay
                //if (User.IsInRole(UserRoles.QPS.ToDescription()))
                //{
                //    var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
                //                            .Select(x => x.Facility).ToList();
                //    if (facilities.Count < 1)
                //    {
                //        allowListing = false;
                //        ViewBag.FacilityAdminMessage = "No Facility assigned to the user. Please contact your system administrator.";
                //    }
                //}
                ViewBag.isSleepAllow = loggedInUser.IsSleep;
                ViewBag.AllowListing = allowListing;
                ViewBag.Error = (TempData["Error"] as bool?) ?? false;
                ViewBag.Message = TempData["StatusMessage"] as string;
                ViewBag.StatusFilter = _uclService.GetUclData(UclTypes.CaseStatus).ToList();
                if (User.IsInRole(UserRoles.Physician.ToDescription()) || User.IsInRole(UserRoles.PartnerPhysician.ToDescription()))
                    ViewBag.iscalculateBill = isCalculateBill;
                else
                    ViewBag.iscalculateBill = false;
                return GetViewResult();
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                return Json(new { success = false, message = "An error has been occurred while processing your request, please try later." });
            }
        }

        [AccessRoles(Roles = "Administrator,Super Admin,Quality Team,Regional Medical Director,Navigator,QPS,RRC Manager,RRC Director,VP Quality, Quality Director,AOC,Capacity Researcher")]
        public ActionResult Dashboard()
        {
            if (TempData.ContainsKey("Message"))
                TempData.Remove("Message");

            bool allowListing = true;
            if (User.IsInRole(UserRoles.FacilityAdmin.ToDescription()))
            {
                var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
                                                         .Select(x => x.Facility)
                                                         .ToList();
                if (facilities.Count < 1)
                {
                    allowListing = false;
                    ViewBag.FacilityAdminMessage = "No Facility assigned to the user. Please contact your system administrator.";
                }
            }
            if (User.IsInRole(UserRoles.FacilityPhysician.ToDescription()))
            {
                var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
                                        .Select(x => x.Facility).ToList();
                if (facilities.Count < 1)
                {
                    allowListing = false;
                    ViewBag.FacilityAdminMessage = "No Facility assigned to the user. Please contact your system administrator.";
                }
            }
            #region Can be used in future for qps facility purpose
            //if (User.IsInRole(UserRoles.QPS.ToDescription()))
            //{
            //    var facilities = _ealertFacilitiesService.GetAllAssignedFacilities(User.Identity.GetUserId())
            //                            .Select(x => x.Facility).ToList();
            //    if (facilities.Count < 1)

TeleSpecialists.Web/Views/FacilityPI/CaseReviewTrends.cshtml
@using TeleSpecialists.BLL.Extensions;


<div class="row">
    <div class="col-md-12 text-center">
        <h3>Case Review Process Trends</h3>
    </div>
</div>
<div class="row">
    <div id="casereviewtrendsGrid">
    </div>
</div>

<script type="text/javascript">
    function getCaseReviewTrends() {
        $("#casereviewtrendsGrid").kendoGrid({
            @*excel: {
                allPages: true,
                filterable: false,
                fileName: '@ViewBag.Title' + '.xlsx',
                proxyURL: '@Url.Action("ExportToExcel")',
            },*@
            dataSource: {
                transport: {
                    read: {
                        url: '@Url.Action("GetCaseReviewTrends")',
                        contentType: "application/json",
                        type: "POST",
                        data: function () {
                            var model = {
                                Facilities: "",
                                System: "",
                                Regional: "",
                                States: "",
                                QPS: "",
                                qag_time_frame: "",
                                fromMonth: "",
                                toMonth: "",
                            };
                            var fac_keys = $("#Facilities").val();
                            if (fac_keys == "") {
                                model.Facilities = null;
                            } else {
                                model.Facilities = $("#Facilities").val();
                            }

                            var system = $("#fac_ucd_key_system").val();
                            if (system == "") {
                                model.System = null;
                            } else {
                                model.System = $("#fac_ucd_key_system").val();
                            }

                            var region = $("#fac_ucd_region_key").val();
                            if (region == "") {
                                model.Regional = null;
                            } else {
                                model.Regional = $("#fac_ucd_region_key").val();
                            }

                            var state = $("#fac_stt_key").val();
                            if (state == "") {
                                model.States = null;
                            } else {
                                model.States = $("#fac_stt_key").val();
                            }

                            var qps = $("#facilityQPS").val();
                            if (qps == "" || qps == "0" || qps == undefined) {
                                model.QPS = null;
                            } else {
                                model.QPS = $("#facilityQPS").val();
                            }
                            var YearFromDate = $("#FromMonth").val();
                            if (YearFromDate) {
                                var year = YearFromDate.split(" ");
                                var timeframe = year[1];
                                if (timeframe) {
                                    model.qag_time_frame = timeframe + '-1-1';
                                }
                            }
                            model.fromMonth = $("#FromMonth").val();
                            model.toMonth = $("#ToMonth").val();
                            localStorage.setItem('QualityMetricsReport.Filter', JSON.stringify(model));
                            return model;
                        },
                        type: "POST"
                    },
                    parameterMap: function (options) {
                        return kendo.stringify(options);
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                },
                //page: KendoGet("QualityGoals", "page"),
                //pageSize: KendoGet("QualityGoals"),
                //serverPaging: true,
                //serverFiltering: true,
                //serverSorting: true
            },
            width: '100%',
            groupable: false,
            filterable: false,
            sortable: false,
            resizable: true,
            
            //pageable: {
            //    refresh: true,
            //    pageSizes: true,
            //    buttonCount: 5
            //},
            dataBound: function (e) {

                $("#kendoDataGrid .k-auto-scrollable").scrollLeft(0);
                // Adjust dropdown horizental allignment in case of five-9 sidebae expanded.
                $('[data-role="dropdownlist"]').each(function () {
                    var kendoDropDown = $(this).data("kendoDropDownList");
                    if (kendoDropDown)
                        kendoDropDown.bind("open", onDropdDownOpen);
                });
            },
            columns: [
                { field: "title", title: "Performance Metric Outliers", width: '110px' },
                { field: "total", title: "Number of Times", width: '110px' },
            ],
            excelExport: function (e) {
                e.preventDefault();

                promises[1].resolve(e.workbook);
            },
        });
        }
</script>

TeleSpecialists.Web/Views/FacilityPI/CounterMeasure.cshtml
@using TeleSpecialists.BLL.Extensions;
@{
    ViewBag.Title = "CounterMeasure";
}


<div class="row">
    <div class="col-md-12 text-center">
        <h3>Countermeasures</h3>
    </div>
</div>
<div class="row">
    <div id="CounterMeasureGrid">
    </div>
</div>
<div class="modal" id="countermeasureModal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" style=" max-width: 1000px; width: 1000px; ">
        <div class="modal-content">
            <div class="modal-header">
            </div>
            <div class="modal-body">
                <div class="countermeasuretable table-wrapper-scroll-y my-custom-scrollbar"></div>
            </div>
            <div class="modal-footer">
                <a class="btn btn-link" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
<style>
    .my-custom-scrollbar {
        position: relative;
        overflow: auto;
    }

    .table-wrapper-scroll-y {
        display: block;
        max-height: 400px;
    }

        .table-wrapper-scroll-y thead th {
            position: sticky;
            top: 0px;
            background-color: white;
        }
</style>
<script type="text/javascript">
    
    function getCounterMeasures() {
        $("#CounterMeasureGrid").kendoGrid({
            excel: {
                allPages: true,
                filterable: false,
                fileName: '@ViewBag.Title' + '.xlsx',
                proxyURL: '@Url.Action("ExportToExcel")',
            },
            dataSource: {
                transport: {
                    read: {
                        url: '@Url.Action("GetCounterMeasure")',
                        contentType: "application/json",
                        type: "POST",
                        data: function () {
                            var model = {
                                Facilities: "",
                                System: "",
                                Regional: "",
                                States: "",
                                QPS: "",
                                qag_time_frame: "",
                                fromMonth: "",
                                toMonth: "",
                            };
                            var fac_keys = $("#Facilities").val();
                            if (fac_keys == "") {
                                model.Facilities = null;
                            } else {
                                model.Facilities = $("#Facilities").val();
                            }

                            var system = $("#fac_ucd_key_system").val();
                            if (system == "") {
                                model.System = null;
                            } else {
                                model.System = $("#fac_ucd_key_system").val();
                            }

                            var region = $("#fac_ucd_region_key").val();
                            if (region == "") {
                                model.Regional = null;
                            } else {
                                model.Regional = $("#fac_ucd_region_key").val();
                            }

                            var state = $("#fac_stt_key").val();
                            if (state == "") {
                                model.States = null;
                            } else {
                                model.States = $("#fac_stt_key").val();
                            }

                            var qps = $("#facilityQPS").val();
                            if (qps == "" || qps == "0" || qps == undefined) {
                                model.QPS = null;
                            } else {
                                model.QPS = $("#facilityQPS").val();
                            }
                            var YearFromDate = $("#FromMonth").val();
                            if (YearFromDate) {
                                var year = YearFromDate.split(" ");
                                var timeframe = year[1];
                                if (timeframe) {
                                    model.qag_time_frame = timeframe + '-1-1';
                                }
                            }
                            model.fromMonth = $("#FromMonth").val();
                            model.toMonth = $("#ToMonth").val();
                            localStorage.setItem('QualityMetricsReport.Filter', JSON.stringify(model));
                            return model;
                        },
                        type: "POST"
                    },
                    parameterMap: function (options) {
                        return kendo.stringify(options);
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total"
                },
                //serverPaging: true,
                //serverFiltering: true,
                //serverSorting: true,
                //pageSize: GetKendoPageSize("QualityReport", "RecPerPage", true),
                //page: KendoGet("QualityReport", "page")
                serverPaging: true,
                pageSize: 50,
                serverFiltering: false,
                serverSorting: true,
            },
            width: '100%',
            pageable: {
                refresh: true,
                //pageSizes: true,
                //pageSize: 10
                pageSizes: [50, 100, 150, 200, 300, 500, 'All']
            },
            groupable: false,
            filterable: true,
            sortable: true,
            resizable: true,
            dataBound: function (e) {

                $("#kendoDataGrid .k-auto-scrollable").scrollLeft(0);
                // Adjust dropdown horizental allignment in case of five-9 sidebae expanded.
                $('[data-role="dropdownlist"]').each(function () {
                    var kendoDropDown = $(this).data("kendoDropDownList");
                    if (kendoDropDown)
                        kendoDropDown.bind("open", onDropdDownOpen);
                });
            },
            columns: [
                {
                    title: "<b>Countermeasures</b>", width: '80px',
                    template: "<input type='button' class='btn btn-dark btn-sm' data-id='#= cas_key#' onclick='showCounterMeasure.call(this)' value='Countermeasures' />"
                },
                {
                    title: "Case Number", width: '80px',
                    template: "<strong>#= casenumber#</strong>"
                }
            ]
        });
    }
    var showCounterMeasure = function () {
        var cas_key = $(this).data("id");
        $.ajax({
            cache: false,
            async: true,
            type: "POST",
            url: '/FacilityPI/GetCounterMeasureModal',
            data: { cas_key: cas_key },
            success: function (data) {
                var ArrFinal = [];
                $.each(data, function (key, value) {
                    ArrFinal.push({ Id: value.rca_rootcause_id, RootCause: value.rca_root_cause, ProposedCountermeasure: value.rca_proposed_countermeasure, ResponsibleParty: value.rca_responsible_party, ProposedDueDate: value.rca_proposed_due_date, CompletedDate: value.rca_completed_date, RootId: value.rca_Id })
                });
                var html = '';
                html += '<table class="table table-bordered table-hover table-striped mb-0">';
                html += '<thead>';
                html += '<tr>';
                html += '<th>Root Cause</th>';
                html += '<th>Countermeasure(s)</th>';
                html += '<th>Responsible Party</th>';
                html += '<th>Proposed Due Date</th>';
                html += '<th>Completed Date</th>';
                html += '</tr>';
                html += '</thead>';
                html += '<tbody>';
                $.each(ArrFinal, function (key, value) {
                    html += '<tr>';
                    html += '<td><p>' + value.RootCause + '</p></td>';
                    html += '<td><p>' + value.ProposedCountermeasure + '</p></td>';
                    html += '<td><p>' + value.ResponsibleParty + '</p></td>';
                    html += '<td><p>' + value.ProposedDueDate + '</p></td>';
                    html += '<td><p>' + value.CompletedDate + '</p></td>';
                    html += '</tr>';
                });
                html += ' </tbody>';
                html += '</table>';
                $(".countermeasuretable").empty();
                $(".countermeasuretable").append(html);
                $("#countermeasureModal").modal('show');
            },
            error: function () {

            }
        });
    }
</script>

TeleSpecialists.Web/Views/FacilityPI/Create.cshtml
@model TeleSpecialists.BLL.Model.quality_goals
@{
    ViewBag.Title = "Add QualityGoals";
}

@Html.Partial("_Form", Model)

TeleSpecialists.Web/Views/FacilityPI/Edit.cshtml
@model TeleSpecialists.BLL.Model.goals_data
@{
    ViewBag.Title = "Edit QualityGoals";
}

@Html.Partial("_Edit", Model)

TeleSpecialists.Web/Views/FacilityPI/tPAcaseanalysis.cshtml
@using TeleSpecialists.BLL.Helpers;
@using TeleSpecialists.BLL.Extensions;
@{
    ViewBag.Title = "TPA Case Analysis";
}


<div class="row">
    <div class="col-md-12 text-center">
        <h3>TPA Cases</h3>
    </div>
</div>
<div class="row">
    <div id="tPAcaseanalysisGrid">
    </div>
</div>

<script type="text/javascript">
    function gettPAanaylysis() {
        $("#tPAcaseanalysisGrid").kendoGrid({
            excel: {
                allPages: true,
                filterable: false,
                fileName: '@ViewBag.Title' + '.xlsx',
                proxyURL: '@Url.Action("ExportToExcel")',
            },
            dataSource: {
                transport: {
                    read: {
                        url: '@Url.Action("GetTPAAnalysis")',
                        contentType: "application/json",
                        type: "POST",
                        data: function () {
                            var model = {
                                Facilities: "",
                                System: "",
                                Regional: "",
                                States: "",
                                QPS: "",
                                qag_time_frame: "",
                                fromMonth: "",
                                toMonth: "",
                            };
                            var fac_keys = $("#Facilities").val();
                            if (fac_keys == "") {
                                model.Facilities = null;
                            } else {
                                model.Facilities = $("#Facilities").val();
                            }

                            var system = $("#fac_ucd_key_system").val();
                            if (system == "") {
                                model.System = null;
                            } else {
                                model.System = $("#fac_ucd_key_system").val();
                            }

                            var region = $("#fac_ucd_region_key").val();
                            if (region == "") {
                                model.Regional = null;
                            } else {
                                model.Regional = $("#fac_ucd_region_key").val();
                            }

                            var state = $("#fac_stt_key").val();
                            if (state == "") {
                                model.States = null;
                            } else {
                                model.States = $("#fac_stt_key").val();
                            }

                            var qps = $("#facilityQPS").val();
                            if (qps == "" || qps == "0" || qps == undefined) {
                                model.QPS = null;
                            } else {
                                model.QPS = $("#facilityQPS").val();
                            }
                            var YearFromDate = $("#FromMonth").val();
                            if (YearFromDate) {
                                var year = YearFromDate.split(" ");
                                var timeframe = year[1];
                                if (timeframe) {
                                    model.qag_time_frame = timeframe + '-1-1';
                                }
                            }
                            model.fromMonth = $("#FromMonth").val();
                            model.toMonth = $("#ToMonth").val();
                            localStorage.setItem('QualityMetricsReport.Filter', JSON.stringify(model));
                            return model;
                        },
                        type: "POST"
                    },
                    parameterMap: function (options) {
                        return kendo.stringify(options);
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total"
                },
                //serverPaging: true,
                //serverFiltering: true,
                //serverSorting: true,
                //pageSize: GetKendoPageSize("QualityReport", "RecPerPage", true),
                //page: KendoGet("QualityReport", "page")
                serverPaging: true,
                pageSize: 50,
                serverFiltering: false,
                serverSorting: true,
            },
            width: '100%',
            pageable: {
                refresh: true,
                //pageSizes: true,
                //pageSize: 10
                pageSizes: [50, 100, 150, 200, 300, 500, 'All']
            },
            groupable: false,
            filterable: true,
            sortable: true,
            resizable: true,
            dataBound: function (e) {

                $("#kendoDataGrid .k-auto-scrollable").scrollLeft(0);
                // Adjust dropdown horizental allignment in case of five-9 sidebae expanded.
                $('[data-role="dropdownlist"]').each(function () {
                    var kendoDropDown = $(this).data("kendoDropDownList");
                    if (kendoDropDown)
                        kendoDropDown.bind("open", onDropdDownOpen);
                });
            },
            columns: [
                { field: "name", title: "Facility", width: '150px' },
                {
                    title: "TeleCare Case #", width: '90px', field: "case_number",
                    template: "<a class='py-1 loadLinkAsync' href='@Url.Action("Edit","Case")/\@(User.IsInRole(UserRoles.QPS.ToDescription()) || User.IsInRole(UserRoles.RegionalMedicalDirector.ToDescription()) || User.IsInRole(UserRoles.MedicalStaff.ToDescription()) ? "?id=#=cas_key#&isReadOnly=#= true#" : "#= cas_key#?showPopupOnLoad=true")'>#= case_number#</a>"
                },
                //{ field: "case_number", title: "TeleCare Case #", width: '70px' },
                { field: "created_date", title: "Date", width: '80px' },
                { field: "process", title: "Process (EMS / WI/ IP / ED)", width: '120px' },
                { field: "doortoneedle", title: "DTN (Min)", width: '90px' },
                { field: "tpanotes", title: "tPA Delay Notes", width: '220px' },
                { field: "qpsanalysis", title: "QPS Analysis", width: '220px' },
                { field: "medicaldirectoranalysis", title: "Medical Director Analysis", width: '220px' }
            ]
        });
        }
</script>