TeleSpecialists.Web/Controllers/PhysicianLicenseController.cs
using System;
using System.Net;
using System.Web.Mvc;
using TeleSpecialists.BLL.Model;
using TeleSpecialists.BLL.Service;
using Kendo.DynamicLinq;
using Microsoft.AspNet.Identity;
using TeleSpecialists.BLL.Extensions;
using System.Linq;
using TeleSpecialists.BLL.Helpers;

namespace TeleSpecialists.Controllers
{
    [Authorize]
    [AccessRoles(Roles = "Super Admin")]
    public class PhysicianLicenseController : BaseController
    {
        private readonly PhysicianLicenseService _physicianLicenseService;
        private readonly LookupService _lookupService;
        private readonly UCLService _uclService;
        
        public PhysicianLicenseController()
        {
            _physicianLicenseService = new PhysicianLicenseService();
            _lookupService = new LookupService();
            _uclService = new UCLService();
        }
        public ActionResult Index(string phy_key)
        {
            ViewBag.phy_key = phy_key;
            return PartialView();
        }
        public ActionResult Create(string phy_key)
        {
            ViewBag.phl_license_state = _uclService.GetUclData(UclTypes.State)
                .Select(m => new SelectListItem
                {
                    Text = m.ucd_description,
                    Value = m.ucd_key.ToString()
                });
            return PartialView(new physician_license { phl_user_key = phy_key,  phl_is_active = true });
        }
        public ActionResult Edit(Guid? id)
        {
            ViewBag.phl_license_state = _uclService.GetUclData(UclTypes.State)
                 .Select(m => new SelectListItem
                 {
                     Text = m.ucd_description,
                     Value = m.ucd_key.ToString()
                 });
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            physician_license physician_license = _physicianLicenseService.GetDetails(id.Value);
            if (physician_license == null)
            {
                return HttpNotFound();
            }
            return PartialView(physician_license);
        }
        // POST: CaseType/Edit/5               
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(physician_license physician_license)
        {
            if (ModelState.IsValid)
            {
                physician_license.phl_modified_by = User.Identity.GetUserId();
                physician_license.phl_modified_date = DateTime.Now.ToEST();
                physician_license.phl_modified_by_name = loggedInUser.FullName;

                _physicianLicenseService.Edit(physician_license);
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false, data = string.Join("<br/>", this.GetModalErrors().Values) });
            }
        }
        public ActionResult Remove(Guid id)
        {
            try
            {
                var model = _physicianLicenseService.GetDetails(id);
                model.phl_modified_by = User.Identity.GetUserId();
                model.phl_modified_date = DateTime.Now.ToEST();
                model.phl_modified_by_name = loggedInUser.FullName;

                model.phl_is_active = false;
                model.phl_expired_date = DateTime.Now.ToEST();
                _physicianLicenseService.Edit(model);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                return Json(new { success = false, data = string.Join("<br/>", this.GetModalErrors().Values) }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Create(physician_license model)
        {
            if (_physicianLicenseService.IsAlreadyExists(model))
                ModelState.AddModelError("", "License already exists");

            if (ModelState.IsValid)
            {
                model.phl_key = Guid.NewGuid();
                model.phl_created_by_name = loggedInUser.FullName;
                model.phl_created_by = User.Identity.GetUserId();
                model.phl_is_active = true;
                model.phl_created_date = DateTime.Now.ToEST();
                _physicianLicenseService.Create(model);
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false, data = string.Join("<br/>", this.GetModalErrors().Values) });
            }
        }
        [HttpPost]
        public ActionResult GetAll(DataSourceRequest request)
        {
            var res = _physicianLicenseService.GetAll(request);
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        #region ----- Disposable -----
        private bool disposed = false; // to detect redundant calls
        protected override void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                    // dispose-only, i.e. non-finalizable logic
                    _physicianLicenseService?.Dispose();
                    _lookupService?.Dispose();
                    _uclService?.Dispose();
                }
                disposed = true;
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

TeleSpecialists.Web/Controllers/UserProfileController.cs
using Kendo.DynamicLinq;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeleSpecialists.BLL.Extensions;
using TeleSpecialists.BLL.Helpers;
using TeleSpecialists.BLL.Service;
using TeleSpecialists.Models;
using TeleSpecialists.BLL.Model;
using TeleSpecialists.Web.Models;
using TeleSpecialists.Web.Hubs;
using System.Collections.Generic;
using System.Data.SqlClient;
using TeleSpecialists.Controllers;
using System.Data.Entity.Validation;
using System.Web;
using System.IO;
using System.Configuration;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Auth;
using Microsoft.Azure.Storage.Blob;
using System.Web.Configuration;

namespace TeleSpecialists.Web.Controllers
{
    public class UserProfileController : BaseController
    {

        private readonly AdminService _adminService;
        private readonly PhysicianService _physicianService;
        private readonly PhysicianStatusService _physicianStatus;
        private readonly PhysicianStatusLogService _physicianStatusLogService;
        private readonly AspNetUsersLogService _userLogService;
        private readonly PhysicianLicenseService _physicianLicenseService;
        private readonly FacilityPhysicianService _facilityPhysicianService;
        private readonly UserProfileServices _UserProfileService;
        public UserProfileController()
        {
            _adminService = new AdminService();
            _physicianService = new PhysicianService();
            _physicianStatus = new PhysicianStatusService();
            _physicianStatusLogService = new PhysicianStatusLogService();
            _userLogService = new AspNetUsersLogService();
            _physicianLicenseService = new PhysicianLicenseService();
            _facilityPhysicianService = new FacilityPhysicianService();
            _UserProfileService = new UserProfileServices();
        }
        [HttpPost]
        public ActionResult GetAll(DataSourceRequest request)
        {
            var res = _physicianLicenseService.GetAll(request);
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetAllPhysicianFacilities(DataSourceRequest request)
        {
            var res = _facilityPhysicianService.GetPhysicianFacilitiesForPhy(request);
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult EditUserProfile()
        {
            try
            {
                var id = loggedInUser?.Id;
                EditProfileViewModel model = new EditProfileViewModel();
                var userDetails = UserManager.Users.Where(x => x.Id == id).Select(x => new EditProfileViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    Username = x.UserName,
                    Email = x.Email,
                    isActive = x.IsActive,
                    isDisable = x.IsDisable,
                    Gender=x.Gender,
                    CreatedDate = x.CreatedDate,
                    Role = x.Roles.FirstOrDefault() != null ? x.Roles.FirstOrDefault().RoleId : "",
                    EnableFive9 = x.EnableFive9,
                    CreatedBy = x.CreatedBy,
                    CreatedByName = x.CreatedByName,
                    MobilePhone = x.MobilePhone,
                    OtherPhone = x.PhoneNumber,
                    UserInitial = x.UserInitial,
                    NPINumber = x.NPINumber,
                    CaseReviewer = x.CaseReviewer,
                    IsEEG = x.IsEEG != null ? (bool)x.IsEEG : false,
                    IsStrokeAlert = x.IsStrokeAlert != null ? (bool)x.IsStrokeAlert : false,
                    NHAlert = x.NHAlert != null ? (bool)x.NHAlert : false,
                    Address_line1 = x.Address_line1,
                    Address_line2 = x.Address_line2,
                    City = x.City,
                    State_key = x.State_key,
                    Zip = x.Zip,
                    TwoFactorEnabled=x.TwoFactorEnabled,
                    PasswordHash = x.PasswordHash,
                    SecurityStamp = x.SecurityStamp,
                    User_Image = x.User_Image,
                    CredentialIndex=x.CredentialIndex,
                    LockoutEndDateUtc = x.LockoutEndDateUtc,
                    LockoutEnabled=x.LockoutEnabled,
                    AccessFailedCount=x.AccessFailedCount,
                    status_key=x.status_key,
                    status_change_cas_key=x.status_change_cas_key,
                    ModifiedByName = x.ModifiedByName,
                    ModifiedBy = x.ModifiedBy,
                    ModifiedDate = x.ModifiedDate,
                    RequirePasswordReset = x.RequirePasswordReset,
                    PasswordExpirationDate = x.PasswordExpirationDate,
                    status_change_date_forAll = x.status_change_date_forAll,
                    IsDeleted=x.IsDeleted,
                    ContractDate=x.ContractDate,
                    APIPassword = x.APIPassword,
                    CredentialCount=x.CredentialCount,
                    status_change_date=x.status_change_date,
                    AddressBlock = x.AddressBlock,
                    PhoneNumberConfirmed=x.PhoneNumberConfirmed,
                    EmailConfirmed=x.EmailConfirmed,
                    IsSleep= x.IsSleep,
                    IsTwoFactVerified= x.IsTwoFactVerified,
                    TwoFactVerifyCode= x.TwoFactVerifyCode,
                    CodeExpiryTime=x.CodeExpiryTime

                }).FirstOrDefault();

                if (userDetails != null)
                {
                    ViewBag.Role = RoleManager.Roles
                                         .Select(m => new SelectListItem
                                         {
                                             Text = m.Name,
                                         }).ToList();

                    model = userDetails;

                    var userRole = RoleManager.Roles.FirstOrDefault(m => m.Id == userDetails.Role);
                    if (userRole != null)
                    {
                        model.Role = userRole.Name;
                    }

                    return GetViewResult(model);
                }
                else
                {
                    TempData["Error"] = true;
                    TempData["StatusMessage"] = "User not found.";
                }
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return GetViewResult();
        }

        [HttpPost]
        public async Task<ActionResult> EditUserProfile(EditProfileViewModel userViewModel, HttpPostedFileBase fileUpload)
        {
            try
            {

                var fileNames = "";
                if (fileUpload != null)
                {
                    fileNames = DateTime.Now.ToString("yyyymmddMMssfff") + System.IO.Path.GetExtension(fileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/"), fileNames);
                    var imagepth = path;
                    fileUpload.SaveAs(imagepth);

                    string connString = ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString;
                    var connStringArray = connString.Split(';');
                    var dictionary = new Dictionary<string, string>();
                    foreach (var item in connStringArray)
                    {
                        var itemKeyValue = item.Split('=');
                        dictionary.Add(itemKeyValue[0], itemKeyValue[1]);
                    }
                    string accountname = dictionary["AccountName"];
                    string accesskeys = dictionary["AccountKey"];
                    string accesskey = accesskeys + "==";
                    string BlobKey = WebConfigurationManager.AppSettings["BlobStroageKey"];
                    var OrigionalImagepath = BlobKey + fileNames;
                    StorageCredentials creden = new StorageCredentials(accountname, accesskey);
                    CloudStorageAccount acc = new CloudStorageAccount(creden, useHttps: true);
                    CloudBlobClient client = acc.CreateCloudBlobClient();
                    CloudBlobContainer cont = client.GetContainerReference("onboarding");
                    cont.CreateIfNotExists();
                    cont.SetPermissions(new BlobContainerPermissions
                    {
                        PublicAccess = BlobContainerPublicAccessType.Blob

                    });
                    CloudBlockBlob cblob = cont.GetBlockBlobReference(fileNames);
                    var LocalImagePath = path.ToString();
                    using (Stream ddd = System.IO.File.OpenRead(@LocalImagePath))

                    {
                        cblob.UploadFromStream(ddd);
                    }
                    fileNames = OrigionalImagepath;
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                }
                else
                {
                    var id = loggedInUser?.Id;
                    fileNames = UserManager.Users.Where(x => x.Id == id).Select(c => c.User_Image).FirstOrDefault();
                }
                AspNetUser editProfileViewModel = new AspNetUser();
                ViewBag.Roles = RoleManager.Roles.ToDictionary(m => m.Id, m => m.Name);
                var user = await UserManager.FindByIdAsync(userViewModel.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

TeleSpecialists.Web/Views/UserProfile/_UserProfileForm.cshtml
@using TeleSpecialists.BLL.Extensions;
@using TeleSpecialists.BLL.Helpers;
@model TeleSpecialists.Models.EditProfileViewModel

<div>
    @using (Html.BeginForm("EditUserProfile", "UserProfile", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "regForm", enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.CreatedBy)
        @Html.HiddenFor(m => m.CreatedByName)
        @Html.HiddenFor(m => m.CreatedDate)
        @Html.HiddenFor(m => m.isActive)
        @Html.HiddenFor(m => m.PasswordHash)
        @Html.HiddenFor(m => m.SecurityStamp)
        @Html.HiddenFor(m => m.NPINumber)
        @Html.HiddenFor(m => m.ModifiedBy)
        @Html.HiddenFor(m => m.ModifiedByName)
        @Html.HiddenFor(m => m.Gender)
        @Html.HiddenFor(m => m.ModifiedDate)
        @Html.HiddenFor(m => m.PasswordExpirationDate)
        @Html.HiddenFor(m => m.RequirePasswordReset)
        @Html.HiddenFor(m => m.EnableFive9)
        @Html.HiddenFor(m => m.CaseReviewer)
        @Html.HiddenFor(m => m.CredentialIndex)
        @Html.HiddenFor(m => m.IsEEG)
        @Html.HiddenFor(m => m.IsStrokeAlert)
        @Html.HiddenFor(m => m.isDisable)
        @Html.HiddenFor(m => m.NHAlert)
        @Html.HiddenFor(m => m.TwoFactorEnabled)
        @Html.HiddenFor(m => m.IsSleep)
        @Html.HiddenFor(m => m.LockoutEndDateUtc)
        @Html.HiddenFor(m => m.LockoutEnabled)
        @Html.HiddenFor(m => m.AccessFailedCount)
        @Html.HiddenFor(m => m.status_key)
        @Html.HiddenFor(m => m.status_change_cas_key)
        @Html.HiddenFor(m => m.APIPassword)
        @Html.HiddenFor(m => m.CredentialCount)
        @Html.HiddenFor(m => m.status_change_date)
        @Html.HiddenFor(m => m.AddressBlock)
        @Html.HiddenFor(m => m.PhoneNumberConfirmed)
        @Html.HiddenFor(m => m.EmailConfirmed)
        @Html.HiddenFor(m => m.status_change_date_forAll)
        @Html.HiddenFor(m => m.IsDeleted)
        @Html.HiddenFor(m => m.ContractDate)
        @Html.HiddenFor(m => m.IsTwoFactVerified)
        @Html.HiddenFor(m => m.TwoFactVerifyCode)
        @Html.HiddenFor(m => m.CodeExpiryTime)
        <div class="row">
            <div class="col-xl-5  col-lg-5 col-md-12 col-sm-12 ">
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">First Name: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Last Name: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Initials: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.UserInitial, new { htmlAttributes = new { @class = "form-control", @placeholder = "Initials", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.UserInitial, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Username: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.Username, new { htmlAttributes = new { @class = "form-control", @placeholder = "Username", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Email: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Mobile Phone: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.MobilePhone, new { htmlAttributes = new { @class = "form-control phone_number", @placeholder = "Mobile Phone" } })
                        @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Other Phone: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.OtherPhone, new { htmlAttributes = new { @class = "form-control phone_number", @placeholder = "Other Phone" } })
                        @Html.ValidationMessageFor(model => model.OtherPhone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Role: </label>
                    <div class="col-lg-8 col-sm-8 col-12">
                        <div>
                            @Html.DropDownListFor(m => m.Role, null, "--select--", new { @class = "form-control", @disabled = "disabled" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xl-6  col-lg-6 col-md-12 col-sm-12)">

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">NPI Number: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.NPINumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "NPI Number", @maxlength = 10, @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.NPINumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Address line 1: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.Address_line1, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address line 1", @maxlength = "100" } })
                        @Html.ValidationMessageFor(model => model.Address_line1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">Address line 2: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.Address_line2, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address line 2", @maxlength = "100" } })
                        @Html.ValidationMessageFor(model => model.Address_line2, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">City: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.City, new { htmlAttributes = new { @class = "form-control", @placeholder = "City", @id = "city", @maxlength = "40" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">State: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        <select id="State_key" name="State_key" class="form-control addValidation" data-selectedValue="@(Model != null ? Model.State_key : 0)"></select>
                        @Html.ValidationMessageFor(model => model.State_key, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-sm-4 col-12">ZIP/Postal Code: </label>
                    <div class="col-xl-6 col-lg-6 col-md-8 col-sm-8 col-12">
                        @Html.EditorFor(x => x.Zip, new { htmlAttributes = new { @class = "form-control", @placeholder = "Zip", @maxlength = "9", @id = "Zips", onkeypress = "return isNumber(event)", @onpaste = "return false" } })
                        <div ParameterName-error> <span id="message"></span></div>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="control-label col-xl-4 col-lg-4 col-md-4 col-sm-4">Upload Image: </label>
                    <div class="col-lg-12 col-xl-8 col-md-8 col-sm-8 col-xs-12">
                        <input type="file" class="form-control" id="fileUpload" name="fileUpload" style="width: 313px;" accept="image/*" />

                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-sm-6 offset-sm-7 offset-md-5 offset-lg-5 text-right">
                <input type="submit" value="Save" class="btn btn-dark" onclick="PostForm('regForm');" id="savebtn" />
            </div>

        </div>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        PostForm("regForm");
    });
    function PostForm(FomId) {
        if ($("#regForm").valid()) {
            $("#" + FomId).on("submit", function (event) {
                event.preventDefault();
                var formData = new FormData(this);
                var frmUrl = $(this).attr('action');
                $.ajax({
                    type: 'post',
                    url: frmUrl,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (e) {

                        hidedivs();
                        getimageid();
                    }
                });

            });
        }
    }
    function hidedivs() {
        $('.removestyle').removeAttr('style');
        $('.removestyle').delay(2000).hide(1000);
    }
    //$("#Zips").on('keypress', function () {
    //    if ($(this).val().length > 8) {
    //        $('#savebtn').prop('disabled', true);
    //        message.css("color", "red");
    //        message.html("Zip code cannot execced from 9");

    //    }
    //});
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>

<script>
    window.setInterval(function () {
        var zpl = $('#Zips').val().length;
        if ( zpl < 10) {
            $('#savebtn').prop('disabled', false);
        }
    }, 1000);
</script>